trigger:
- master
 
pool:
  vmImage: 'windows-latest'
 
steps:
 
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'
 
- script: |
    npm install
  displayName: 'NpmInstall'
 
- script: |
    npm run build
  displayName: 'NpmBuild'
 
- task: PublishPipelineArtifact@1
  inputs:
    artifactName: AngularLogin
    targetPath: '$(Build.SourcesDirectory)/dist'
    publishLocation: 'pipeline'
  displayName: 'PublishNpmArtifact'